# This YAML file will run automated Slack updates from GitHub

name: Node.js CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  schedule:
    # - cron: '0 8 * * *' # remove comment to run on schedule

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    env:
      PW: ${{ secrets.PW }}
      SlackKey: ${{ secrets.SlackKey }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: List files in directory
        run: |
          ls -a
      - name: Install dependencies
        run: npm install
      - name: Start the application
        run: npm start